name: CI

on: push

jobs:
  release:
    name: Test & Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install -g yarn
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Config Yarn Cache Directory
        run: yarn config set cache-folder ~/.yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test --ci
      - name: Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
